const DEBUG_MODE = true;
const worldSize = 30000;
const foodAmount = 500;
const BOT_COUNT = 30;
const BOT_NAMES = ['Slinky', 'Noodle', 'Worminator', 'Sir Hiss', 'Pretzel', 'Zippy', 'Slitherin', 'Boop', 'Mr. Wiggles', 'Snek'];
const SPAWN_BUFFER = 800;
const BOT_BOUNDARY_BUFFER = 500;

const FOOD_TYPES = [
    { radius: 4, score: 1, color: '#FF6347' },
    { radius: 6, score: 2, color: '#FFD700' },
    { radius: 8, score: 3, color: '#ADFF2F' },
    { radius: 10, score: 4, color: '#8A2BE2' }
];

const POWERUP_TYPES = [
    { type: 'FOOD_MAGNET', color: '#FFFFFF', radius: 12 }
];

const gridCellSize = 200;

// Game Loop and Physics Constants
const GAME_TICK_RATE_MS = 1000 / 60; // 60 FPS
const NETWORK_UPDATE_RATE_MS = 1000 / 30; // 30 FPS for network updates
const POWERUP_SPAWN_INTERVAL_MS = 15000;
const MIN_POWERUPS = 5;
const FOOD_MAGNET_RADIUS = 200;
const FOOD_MAGNET_FORCE = 0.1;
const BASE_SPEED_MIN = 3;
const BASE_SPEED_MAX_INITIAL = 4;
const LENGTH_DIVISOR_SPEED = 1000;
const TURN_RATE_MIN = 0.05;
const TURN_RATE_MAX_INITIAL = 0.1;
const LENGTH_DIVISOR_TURN_RATE = 1000;
const BOOST_SPEED_MULTIPLIER = 1.8;
const BOOST_LENGTH_CONSUMPTION_RATE = 0.05;
const BOOST_FOOD_DROP_PROBABILITY = 0.1;
const BOOST_MIN_BODY_LENGTH_FOR_FOOD_DROP = 5;
const BOT_MANAGEMENT_INTERVAL_MS = 5000;
const MIN_BOT_COUNT = 5;
const BOT_COUNT_HUMAN_MULTIPLIER = 2;
const SNAKE_SEGMENT_RADIUS = 6; // New constant for snake body segment radius

// AI Constants
const AI_VISION_RANGE_DIMENSION = 800; // Half width/height for vision range
const AI_VISION_RANGE_WIDTH = 1600; // Full width/height for vision range
const AI_THREAT_SIZE_RATIO = 1.2;
const AI_FLEE_THRESHOLD_BASE = 300;
const AI_FLEE_THRESHOLD_INCREASED = 500;
const AI_FLEE_THRESHOLD_SIZE_RATIO = 2;
const AI_ATTACK_THRESHOLD = 500;
const AI_ATTACK_SIZE_ADVANTAGE = 1.1;
const AI_SENSOR_LENGTH_MULTIPLIER = 5;
const AI_GOAL_VECTOR_WEIGHT = 10.0;
const AI_AVOIDANCE_VECTOR_WEIGHT = 0.5;
const AI_STEERING_MAGNITUDE_THRESHOLD = 0.01;

module.exports = {
    worldSize,
    foodAmount,
    BOT_COUNT,
    BOT_NAMES,
    SPAWN_BUFFER,
    BOT_BOUNDARY_BUFFER,
    FOOD_TYPES,
    POWERUP_TYPES,
    gridCellSize,

    // Export new constants
    GAME_TICK_RATE_MS,
    NETWORK_UPDATE_RATE_MS, // Export the new constant
    POWERUP_SPAWN_INTERVAL_MS,
    MIN_POWERUPS,
    FOOD_MAGNET_RADIUS,
    FOOD_MAGNET_FORCE,
    BASE_SPEED_MIN,
    BASE_SPEED_MAX_INITIAL,
    LENGTH_DIVISOR_SPEED,
    TURN_RATE_MIN,
    TURN_RATE_MAX_INITIAL,
    LENGTH_DIVISOR_TURN_RATE,
    BOOST_SPEED_MULTIPLIER,
    BOOST_LENGTH_CONSUMPTION_RATE,
    BOOST_FOOD_DROP_PROBABILITY,
    BOOST_MIN_BODY_LENGTH_FOR_FOOD_DROP,
    BOT_MANAGEMENT_INTERVAL_MS,
    MIN_BOT_COUNT,
    BOT_COUNT_HUMAN_MULTIPLIER,
    SNAKE_SEGMENT_RADIUS,

    // Export AI constants
    AI_VISION_RANGE_DIMENSION,
    AI_VISION_RANGE_WIDTH,
    AI_THREAT_SIZE_RATIO,
    AI_FLEE_THRESHOLD_BASE,
    AI_FLEE_THRESHOLD_INCREASED,
    AI_FLEE_THRESHOLD_SIZE_RATIO,
    AI_ATTACK_THRESHOLD,
    AI_ATTACK_SIZE_ADVANTAGE,
    AI_SENSOR_LENGTH_MULTIPLIER,
    AI_GOAL_VECTOR_WEIGHT,
    AI_AVOIDANCE_VECTOR_WEIGHT,
    AI_STEERING_MAGNITUDE_THRESHOLD,
    DEBUG_MODE
};